language: go

git:
    depth: 1

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
    - sudo dpkg -i hugo_0.74.3_Linux-64bit.deb
    - git submodule update --init --recursive

script:
    - hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $token
    local_dir: public
    repo: KayneWang/KayneWang.github.io
    target_branch: master
    email: w.zengkai@foxmail.com
    name: KayneWang
    on:
        branch: master