git:
    depth: 1

install:
    - curl -L0
    https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
    - sudo dpkg -i hugo_0.74.3_Linux-64bit.deb

script:
    - hugo

deploy:
    provider: pages
    skip_cleanup: true
    github_token: token
    on:
        branch: master
        local_dir: public
        repo: KayneWang/KayneWang.github.io
        target_branch: master
        email: w.zengkai@foxmail.com
        name: KayneWang